# Arrays
* pip3 install array
# type conda prompt


In [5]:
import array as arr

In [6]:
a=arr.array('i',[1,2,3,7,5])
b=arr.array('d',[1.2,3.0,5.4,9.5])

In [7]:
a

array('i', [1, 2, 3, 7, 5])

In [8]:
b

array('d', [1.2, 3.0, 5.4, 9.5])

In [9]:
len(a)

5

In [10]:
len(b)

4

In [11]:
a.append(83)

In [12]:
a

array('i', [1, 2, 3, 7, 5, 83])

In [13]:
a.remove(3)

In [14]:
a

array('i', [1, 2, 7, 5, 83])

In [18]:
b.append(4)

In [19]:
b

array('d', [1.2, 3.0, 5.4, 9.5, 4.0, 4.0])

In [21]:
a[4]

83

In [22]:
b[3]

9.5

In [23]:
b.pop(3)

9.5

In [24]:
b

array('d', [1.2, 3.0, 5.4, 4.0, 4.0])

In [25]:
a[::-1]

array('i', [83, 5, 7, 2, 1])

In [27]:
b[0:-2]

array('d', [1.2, 3.0, 5.4])

In [28]:
a.index(2)

1

In [29]:
b.index(4)

3

In [30]:
a.insert(2,12)

In [31]:
a

array('i', [1, 2, 12, 7, 5, 83])

In [32]:
c=arr.array('i',[3,5,9,0,45])

In [33]:
a+c

array('i', [1, 2, 12, 7, 5, 83, 3, 5, 9, 0, 45])

# Numpy
* pip3 install numpy

In [38]:
import numpy as np

In [39]:
a=np.array([[1,2,3],[4,2,5],[7,6,9]])

In [40]:
a

array([[1, 2, 3],
       [4, 2, 5],
       [7, 6, 9]])

In [41]:
b=np.array([[4,2,2],[7,1,3],[4,2,34]])

In [42]:
b

array([[ 4,  2,  2],
       [ 7,  1,  3],
       [ 4,  2, 34]])

In [43]:
a.dtype

dtype('int32')

In [44]:
b.dtype

dtype('int32')

In [45]:
a.size

9

In [46]:
a[:2]

array([[1, 2, 3],
       [4, 2, 5]])

In [47]:
b[::-1]

array([[ 4,  2, 34],
       [ 7,  1,  3],
       [ 4,  2,  2]])

In [48]:
a+b

array([[ 5,  4,  5],
       [11,  3,  8],
       [11,  8, 43]])

In [49]:
a*b

array([[  4,   4,   6],
       [ 28,   2,  15],
       [ 28,  12, 306]])

In [50]:
a/b

array([[0.25      , 1.        , 1.5       ],
       [0.57142857, 2.        , 1.66666667],
       [1.75      , 3.        , 0.26470588]])

In [51]:
a-b

array([[ -3,   0,   1],
       [ -3,   1,   2],
       [  3,   4, -25]])

In [52]:
type(a)

numpy.ndarray

In [53]:
a.ndim

2

In [54]:
a.shape

(3, 3)

In [55]:
type(b)

numpy.ndarray

In [56]:
c=np.zeros((3,4))

In [57]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
d=np.array([[2,4,1],[7,5,4]],dtype = 'float')

In [59]:
d

array([[2., 4., 1.],
       [7., 5., 4.]])

In [60]:
a.max()

9

In [61]:
b.min()

1

In [62]:
b.max()

34

In [63]:
a.max(axis=1)

array([3, 5, 9])

In [64]:
a.sum()

39

In [65]:
b.sum()

59

In [66]:
a.sort(axis=0)

In [67]:
a

array([[1, 2, 3],
       [4, 2, 5],
       [7, 6, 9]])

In [68]:
a.sort(axis=1)

In [69]:
a

array([[1, 2, 3],
       [2, 4, 5],
       [6, 7, 9]])

In [70]:
np.diag(a)

array([1, 4, 9])

In [71]:
np.diag(b)

array([ 4,  1, 34])

In [72]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 3.        ]])

In [73]:
np.sqrt(b)

array([[2.        , 1.41421356, 1.41421356],
       [2.64575131, 1.        , 1.73205081],
       [2.        , 1.41421356, 5.83095189]])

In [74]:
np.trace(a)

14

In [75]:
np.trace(b)

39

In [76]:
np.trace(a+b)

53